Optimization trajectory workflow
CitrineInformatics/smlb pull request #6
Opened 2020-09-30 15:32 UTC by bfolie

Prototype of a workflow to study optimization techniques. Includes one optimizer (random sampling) and one scorer (likelihood of improvement). This PR develops a system for tracking every function evaluation call made, independent of optimization technique. It also develops a way to store optimization results.

The goal of this PR is to review the structure. The following are easier follow-ons:
 * Add more scorers
 * Add more optimizers
 * Make the optimization trajectory plot more visually appealing (plot the median trajectory and shade the quantiles, as opposed to plotting individual points)
 * Add an identity learner , which can be used to do optimization on synthetic functions (as opposed to models trained on data drawn from synthetic functions)
 * Add an evaluation that displays information like "fraction of trajectories reaching target Y after X function evaluations" in a table

2020-10-06 17:40 UTC, gregor-robinson requested changes
* OptimizerResults seems to keep track of trajectories, and OptimizerTrajectory seems to keep track of an ensemble of trajectories. This was confusing when first reading the code.

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/optimizer.py
> +    def scores_per_evaluation(self) -> Sequence[float]:
Many DFO algorithms perform multiple function evaluations per optimizer iteration. Especially in cases of optimization of noisy functions (in the context of stochastic Gaussian smoothing, for example) there may not be a sensible way to score each function evaluation. To accommodate this behavior, I suggest recording the score at the completion of one optimizer iteration, along with the number of function evaluations performed during that iteration (or a running total thereof). But on second read, I see how this object records the score for a single optimizer iteration. What's the goal behind that?

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/optimizer.py
> +class OptimizerResults:
Is this not a single trajectory?

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/optimizer.py
> +    def optimize(
How do you feel about calling this method `minimize`? This would mirror scipy and makes explicit what kind of optimization it is.

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/optimizer.py
> +            dataset determines its own domain.
```suggestion
            optimization domain is taken to be that of `data` parameter passed to `optimize()`.
```

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/optimizer.py
> +            function_tracker: a combination of a trained learner, which evaluates data points,
```suggestion
            function_tracker: an instance of TrackedTransformation to track function evaluations and scores.
```

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/optimizer.py
> +            A sequence of OptimizerIteration objects, one for every single function evaluation
Echoing comment above: one per function evaluation isn't always applicable

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/scorer.py
> +            or below the target (minimize). Tune objectives are not supported at this time.
What is the meaning of "tune objectives"?

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/scorer.py
> +    def __init__(self, target: float, goal: str = "maximize", **kwargs):
I think the interface might be easier to replace the string-valued `goal` with a boolean-valued `minimize`. Also, I find it confusing that `optimize` performs minimization (negatively-oriented objective) but here the score is positively-oriented by default.

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/scorer.py
> +class LikelihoodOfImprovement(Scorer):
At risk of dying on this hill, we really should be calling this ProbabilityOfImprovement, especially for open source projects. It is not a likelihood, and the community term is PI.

2020-10-06 17:40 UTC, gregor-robinson commented on smlb/scorer.py
> +        we should have the `PredictiveDistribution` class expose a `cdf()` method.
:100:

2020-10-06 17:40 UTC, gregor-robinson commented on workflows/optimization_trajectories.py
> +    def run(self):
This could use an rng param.

2020-10-06 17:40 UTC, gregor-robinson commented on workflows/optimization_trajectories.py
> +"""Optimization trajectories for multiple optimization algorithms on a single response surface.
This could also be useful for trying different initial conditions / training data on the same response surface, right?

2020-10-06 17:40 UTC, gregor-robinson commented on workflows/optimization_trajectories.py
> +                LearningCurveRegression. But it's unclear if there's anything else we might want
I would also want to see what the present score is, alongside the cumulative best -- it's useful to see divergence even if the best score looks good.

2020-10-06 17:55 UTC, bfolie commented on smlb/optimizer.py
> +class OptimizerResults:
Yes, this is a single trajectory

2020-10-06 18:08 UTC, bfolie commented
> * OptimizerResults seems to keep track of trajectories, and OptimizerTrajectory seems to keep track of an ensemble of trajectories. This was confusing when first reading the code.

`OptimizerIteration` keeps track of a single iteration, where I have defined an iteration to be a single call to an `apply` method. `OptimizerResults` is a sequence of iterations, so I'd agree that's a trajectory. I also agree that `OptimizationTrajectory` is not a good name for the workflow, which is essentially a set of trajectories each one with some metadata about.

The term "iteration" is loosely defined and may mean different things to different optimization algorithms, but I argue that "a single call to `apply`" is a useful definition of iteration both in terms of general benchmarking and to derive conclusions that are relevant to our own software. There are efficiency gains to applying a model to many test points in parallel. Any time the algorithm determines a new batch of points to apply the model to there is additional overhead.

2020-10-06 18:14 UTC, bfolie commented on smlb/optimizer.py
> +    def scores_per_evaluation(self) -> Sequence[float]:
If the algorithm performs the evaluations, applies some logic to decide if it should evaluate again, then performs another evaluation, I'd call that 2 iterations. If the model is evaluated at the same point multiple times with one call, then that will be considered a single iteration.
However I don't think we need to consider stochastic functions here. The way these interfaces are defined, model application can return a definite value or it can return a distribution. But the distribution is fully defined--there's no need to query it multiple times. Therefore we can score each point evaluated in the iteration _or_ we can score the entire iteration as a batch.
We will have to consider stochastic evaluation in a sequential learning workflow.

2020-10-06 18:24 UTC, bfolie commented on smlb/optimizer.py
> +            A sequence of OptimizerIteration objects, one for every single function evaluation
I should change this to be "learner application", for I have defined it to be so

2020-10-06 18:34 UTC, bfolie commented on smlb/optimizer.py
> +    def optimize(
I do not think we should, since this is a user-facing method and we allow for both max- and minimization (for example, it wouldn't make sense to minimize a "probability of improvement" score).

It would, however, make sense to rename the internal method to `_maximize` or `_minimize` to signal to people adding new types of optimizers what the convention is

2020-10-06 18:34 UTC, bfolie commented on smlb/scorer.py
> +class LikelihoodOfImprovement(Scorer):
ok

2020-10-06 18:35 UTC, bfolie commented on smlb/scorer.py
> +            or below the target (minimize). Tune objectives are not supported at this time.
Trying to achieve a specific value. I only wrote it because mslb includes tune objectives, but it's esoteric enough that I should just remove the comment

2020-10-06 18:35 UTC, bfolie commented on workflows/optimization_trajectories.py
> +"""Optimization trajectories for multiple optimization algorithms on a single response surface.
yes

2020-10-06 18:36 UTC, bfolie commented on workflows/optimization_trajectories.py
> +                LearningCurveRegression. But it's unclear if there's anything else we might want
So you could examine the trajectory itself? Makes sense

2020-10-06 21:35 UTC, gregor-robinson commented on smlb/optimizer.py
> +    def scores_per_evaluation(self) -> Sequence[float]:
The specific problem I'm imagining is trust region methods with a stochastic component, where the optimizer decides whether it has enough data to accept or reject a move. For example: https://arxiv.org/pdf/1803.10173.pdf
When it doesn't have enough data to decide whether the move (and therefore the trust region) is valid, it performs more function evaluations drawn from a Guassian distribution around the proposal and the current iterate. But these evaluations are not the same as optimizer iterates.

2020-10-06 21:43 UTC, gregor-robinson commented on workflows/optimization_trajectories.py
> +                LearningCurveRegression. But it's unclear if there's anything else we might want
Yep, exactly

2020-10-06 21:45 UTC, bfolie commented on smlb/optimizer.py
> +    def scores_per_evaluation(self) -> Sequence[float]:
That paper is specifically for noisy functions, which is not something we need to consider.

If we were to consider an algorithm like the one you describe, every time it asks "should I perform more function evaluations?", decides to, samples some points around the current point, and applies the model to those points, that's a new iteration. The authors of the algorithm might not define it as a new iteration, but from the vantage point of asking "how efficient is this algorithm" that's essentially what it is. And all the points sampled can be scored and they they can be proposed as candidates.

2020-10-06 21:48 UTC, gregor-robinson commented
> > * OptimizerResults seems to keep track of trajectories, and OptimizerTrajectory seems to keep track of an ensemble of trajectories. This was confusing when first reading the code.
> 
> `OptimizerIteration` keeps track of a single iteration, where I have defined an iteration to be a single call to an `apply` method. `OptimizerResults` is a sequence of iterations, so I'd agree that's a trajectory. I also agree that `OptimizationTrajectory` is not a good name for the workflow, which is essentially a set of trajectories each one with some metadata about.
> 
> The term "iteration" is loosely defined and may mean different things to different optimization algorithms, but I argue that "a single call to `apply`" is a useful definition of iteration both in terms of general benchmarking and to derive conclusions that are relevant to our own software. There are efficiency gains to applying a model to many test points in parallel. Any time the algorithm determines a new batch of points to apply the model to there is additional overhead.

Optimization benchmarking routinely distinguishes `number of function evaluations` from `number of iterations`. E.g. `nit` versus `nfev`. I find this a very useful separation of concerns, especially to reason about the impact of an expensive step within the optimizer (such as the quadratic programming subproblem for most trust region methods). But I do agree that the number of function evaluations is the most relevant thing for most of our questions at hand.

2020-10-06 21:58 UTC, gregor-robinson commented on smlb/optimizer.py
> +    def scores_per_evaluation(self) -> Sequence[float]:
> That paper is specifically for noisy functions, which is not something we need to consider.

I disagree. It's specifically for discontinuous "deterministic noise" common in computational models, which is precisely the complication introduced by random forests.

> If we were to consider an algorithm like the one you describe, every time it asks "should I perform more function evaluations?", decides to, samples some points around the current point, and applies the model to those points, that's a new iteration. The authors of the algorithm might not define it as a new iteration, but from the vantage point of asking "how efficient is this algorithm" that's essentially what it is. And all the points sampled can be scored and they they can be proposed as candidates.

I can appreciate this argument, but there _is_ an important distinction between a step of the algorithm (what I would call an iteration) and the proposal stage. The function evaluations at the sampled points are not direct observations of the objective, so I don't agree they can be scored as such.

2020-10-06 21:59 UTC, bfolie commented on smlb/scorer.py
> +    def __init__(self, target: float, goal: str = "maximize", **kwargs):
Agree that a boolean is better. I was actually going to have the optimization algorithms perform maximization, but I'll change that to minimization to fit with scipy. I'll still leave the user-facing default as "maximize", though, since in the typical case this will be a score.

2020-10-06 22:53 UTC, bfolie commented on workflows/optimization_trajectories.py
> +    def run(self):
Actually, I think that the pattern is to put the random mix-in in the class itself. `RandomOptimizer`, for example, extends `Random` so it must be instantiated with an `rng` parameter. But the learners don't extend `Random`. I filed an issue to change that https://github.com/CitrineInformatics/smlb/issues/7

2020-10-06 22:54 UTC, bfolie commented on workflows/optimization_trajectories.py
> +"""Optimization trajectories for multiple optimization algorithms on a single response surface.
I updated the docstring

2020-10-06 22:55 UTC, bfolie commented on workflows/optimization_trajectories.py
> +                LearningCurveRegression. But it's unclear if there's anything else we might want
I updated the TODO, but would you mind if I punted on this? It's not clear exactly how the trajectories would be evaluated and I think that will inform the abstraction, so it will be easier to wait until we have a specific analysis we want to see.

2020-10-06 23:05 UTC, bfolie commented
> Optimization benchmarking routinely distinguishes `number of function evaluations` from `number of iterations`. E.g. `nit` versus `nfev` in scipy (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html). I find this a very useful separation of concerns, especially to reason about the impact of an expensive step within the optimizer (such as the quadratic programming subproblem for most trust region methods). But I do agree that the number of function evaluations is the most relevant thing for most of our questions at hand.

To be clear, we are tracking iterations and function evaluations separately here. An iteration is a single application of a learner _to a dataset_, and that dataset can include many points that are evaluated.

I agree that it's a useful separation of concerns, but because the term "iteration" is loosely defined it's not very useful for comparing across algorithms. When I was messing around a bit with scipy's dual annealing, a several-thousand function evaluation optimization would generally report only 5-10 iterations. What does that mean? How can we compare that to a different algorithm that might define "iteration" differently?

The scipy algorithms don't expose enough information for us to enforce a strict definition of "iteration", so we'll just end up comparing function evaluations. But this concept will be useful if we want to implement/extend existing algorithms or combine optimization with batch construction.

2020-10-07 00:19 UTC, gregor-robinson commented on workflows/optimization_trajectories.py
> +                LearningCurveRegression. But it's unclear if there's anything else we might want
Yep, that's fine by me

2020-10-07 00:51 UTC, gregor-robinson approved these changes
LTGM. Thanks for the video chat; I think that cleared up a lot and I'm happy with this update.

2020-10-07 10:27 UTC, matthias-rupp commented
> > Optimization benchmarking routinely distinguishes `number of function evaluations` from `number of iterations`.
> To be clear, we are tracking iterations and function evaluations separately here.

It seems important to me to track both. For the comparison of algorithms part, the number of function evaluations seems a good standard criterion to look at, will often be the more interesting statistic, and is comparable. For some scenarios, the number of iterations might be important (e.g., interest in minimum number of iterations/batches/...).

2020-10-07 18:27 UTC, bfolie commented
> It seems important to me to track both. For the comparison of algorithms part, the number of function evaluations seems a good standard criterion to look at, will often be the more interesting statistic, and is comparable. For some scenarios, the number of iterations might be important (e.g., interest in minimum number of iterations/batches/...).

For now we're going to track function evaluations and what is now called "steps," where 1 step is one application of `learner.apply` (possibly to a dataset with `N > 1` data points, meaning there will be `N` function evaluations).

An "iteration" is more loosely defined as "a series of steps and function evaluations that lead to the optimizer producing a new candidates that it has reason to think will be an optimum." I don't think this information is very useful from a basic "which optimizer gets the best result in the least time?" point of view, but Gregor pointed out that it can be useful for diagnosing how the algorithm is behaving and making improvements to its behavior. Since scipy exposes this information as [OptimizerResult](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult) I'm going to see if we can adapt that interface or something similar.

2020-10-07 18:27 UTC, merged